version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.2

    working_directory: ~/video_converter

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install --upgrade pip setuptools wheel
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . .venv/bin/activate
            export PYTHONPATH='../video_converter/'
            pytest -v --cov